//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLPWordAddIn.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\fil1klp\\data\\FileNet-Import-Batch\\documents\\skade")]
        public string FileServerPath {
            get {
                return ((string)(this["FileServerPath"]));
            }
            set {
                this["FileServerPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\DocTimTempFiles")]
        public string LocalTempFolder {
            get {
                return ((string)(this["LocalTempFolder"]));
            }
            set {
                this["LocalTempFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\fnbp1klp\\FileNet-Import-Batch\\FileNet-Skade_DocList\\DocumentCodes.xml")]
        public string DocumentCodesFileLocation {
            get {
                return ((string)(this["DocumentCodesFileLocation"]));
            }
            set {
                this["DocumentCodesFileLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\fnbp1klp\\FileNet-Import-Batch\\FileNet-Skade_DocList\\DocumentCodes.xml")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\Microsoft\\KLPOffice2013ToolsSetup\\DocumentCodes.xml")]
        public string DocumentCodesFileLocationLocalTest {
            get {
                return ((string)(this["DocumentCodesFileLocationLocalTest"]));
            }
            set {
                this["DocumentCodesFileLocationLocalTest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\Microsoft\\KLPOffice2013ToolsSetup\\EnvironmentConfiguration" +
            ".xml")]
        public string EnvironmentConfigurationFile {
            get {
                return ((string)(this["EnvironmentConfigurationFile"]));
            }
            set {
                this["EnvironmentConfigurationFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\Microsoft\\KLPOffice2013ToolsSetup\\EnvironmentConfiguration" +
            ".xml")]
        public string LocalEnvironmentConfigurationFile {
            get {
                return ((string)(this["LocalEnvironmentConfigurationFile"]));
            }
            set {
                this["LocalEnvironmentConfigurationFile"] = value;
            }
        }
    }
}
